### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Brutuss** [buildxyz-git/nixiclock_ncs314#2]
Hi, I'm trying to compile this firmware on my Arduino Mega.

I added the Rtttl Library from your Github. I am compiling with Arduino IDE 1.8.13 on Windows 10. 

In file included from sketch\NixieShield.h:1:0,
                 from C:\Users\Michaël vd Heijden\Downloads\nixiclock_ncs314-master\nixiclock_ncs314-master\NixieClock_NCS314_Firmware\NixieClock_NCS314_Firmware.ino:23:
C:\Users\Micha�l vd Heijden\Documents\Arduino\libraries\Rtttl\src/Rtttl.h:18:10: fatal error: Flash.h: No such file or directory
 #include <Flash.h>
          ^~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Mega or Mega 2560

**Comment by buildxyz-git** [comment]
Hi, the rtttl library requires [this ](http://arduiniana.org/libraries/flash/) library to be installed. I'll update the instructions for this project with that information later. 

I do see that the flash library uses a deprecated type when I just tried compiling and it failed on the latest Arduino IDE. So You can:
 
1. Change the prog_char references in the flash lib as shown [here](https://forum.arduino.cc/index.php?topic=533662.0).

2. Use an older Arduino to compile the project.

**Comment by Brutuss** [comment]
Hi, thanx for you quick reply. Unfortunately I'm unable to solve the problem.

I downloaded the extra Library and then I tried the easy way and downloaded some older Arduino versions en tested it. The results are below:

**1.0 -- >1.5.0**
In file included from /NixieShield.h:10,
                 from NixieClock_NCS314_Firmware.ino:23:
NixieClock_NCS314_utils.h:10: error: 'String' does not name a type
NixieClock_NCS314_utils.h:14: error: 'byte' does not name a type
NixieClock_NCS314_utils.h:16: error: 'byte' does not name a type
NixieClock_NCS314_utils.h:25: error: 'word' does not name a type
NixieClock_NCS314_utils.h:26: error: 'word' does not name a type
In file included from /NixieShield.h:11,
                 from NixieClock_NCS314_Firmware.ino:23:
NixieConfig.h:100: error: expected constructor, destructor, or type conversion before '(' token
NixieConfig.h:100: error: expected unqualified-id before ')' token

**1.5.8 and 1.6.0**
In file included from NixieClock_NCS314_Firmware.ino:23:0:
NixieShield.h:1:71: fatal error: Rtttl.h: No such file or directory
 #include <Rtttl.h>              // https://github.com/spicajames/Rtttl
                                                                       ^
compilation terminated.

**1.6.13 --> 1.8.13**
C:\Users\Michaël vd Heijden\Documents\Arduino\libraries\Flash/Flash.h:70:23: error: 'prog_char' does not name a type _FLASH_STRING(const prog_char *arr);

Then I tried editing the Flash.h file. But i think I'm doing it wrong. 

First I changed replaced all the fields containing "prog_char" with "PGM_P" that results in: 

C:\Users\Michaël vd Heijden\Documents\Arduino\libraries\Flash/Flash.h:70:23: error: duplicate 'const'
 _FLASH_STRING(const PGM_P *arr);

Then I Replaced "const prog_char" to "PGM_P" with the below result: 

"C:\Users\Michaël vd Heijden\Documents\Arduino\libraries\Flash/Flash.h: In member function 'size_t _FLASH_STRING::length() const':

C:\Users\Michaël vd Heijden\Documents\Arduino\libraries\Flash/Flash.h:73:25: error: cannot convert 'const char** const' to 'const char*' for argument '1' to 'size_t strlen_P(const char*)'

   { return strlen_P(_arr); }

I'm not a programmer :( so I try to understand but this is above my head. 

Thnx again.

**Comment by buildxyz-git** [comment]
Bummer!

I have just pushed some changes and can confirm it is compiling for me on Windows 10 running Arduino IDE version 1.8.13 The changes include:

- All the libraries are now included verbatim for you to copy directly to your Arduino library directory
- The compiled .hex image for direct flashing if you wish to not configure anything yourself.

So I would start with a fresh clone of this repo and delete all the existing libraries in your Arduino library directory.

**Comment by Brutuss** [comment]
I can confirm it to! Thank you for your help!

**Comment by siwar31** [comment]
hello is there anyone here can help me am triying to program with arduino mega for a project but iam blocked cause im not a programmer if anyone can help

**Comment by Brutuss** [comment]
Siwar maybe you can explain here what isn't working. And one advise hide your email address to the internet because you will get a lot of spam this way.

**Comment by siwar31** [comment]
Thanks for replying and for the advice .. I have a problem I I don't know
how to apload a video in my sql .. am trying to to do a data base that with
3 colomns one for the identificator one for the problem name and one for
the video

**Comment by Brutuss** [comment]
Unfortunately this has nothing to do with this project. So I'm afraid I can't help you either. Sorry.
